close_when_open = true
theme = "monokai"
theme_base = []
theme_location = ["./themes"]
hotreload_theme = true
force_keyboard_focus = true
timeout = 60

[keys.ai]
run_last_response = ["ctrl e"]

[list]
max_entries = 200
cycle = true

[search]
placeholder = " Search..."

[providers]
default = ["desktopapplications"]

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "."
provider = "unicode"

[[providers.prefixes]]
prefix = ":"
provider = "symbols"

[providers.desktopapplications]
launch_prefix = "uwsm app -- "
placeholder = " Search..."
prioritize_new = false
context_aware = false
show_sub_when_single = false
history = false
icon = ""

[providers.desktopapplications.actions]
enabled = false
hide_category = true

[providers.files]
use_fd = true
cmd_alt = "xdg-open $(dirname ~/%RESULT%)"
icon = "file"
name = "Finder"
preview_images = true

[providers.symbols]
name = "Emojis"
icon = ""

[providers.windows]
switcher_only = true

[providers.bookmarks]
hidden = true

[[providers.bookmarks.entries]]
label = "Omarchy - Github"
url = "https://github.com/basecamp/omarchy"
keywords = ["omarchy", "github"]

[[providers.bookmarks.entries]]
label = "Omarchy Manual"
url = "https://manuals.omamix.org/2/the-omarchy-manual"
keywords = ["omarchy"]
