hl.env("SSH_AUTH_SOCK",               "$XDG_RUNTIME_DIR/ssh-agent.socket")
hl.env("GTK_THEME",                   "WhiteSur")
hl.env("GTK_ICON_THEME",              "breeze")
hl.env("ICON_THEME",                  "breeze")
hl.env("GTK_USE_PORTAL",              "1")
hl.env("XCURSOR_THEME",               "Quintom_Ink")
hl.env("XCURSOR_SIZE",                "20")
hl.env("QT_QPA_PLATFORM",             "wayland")
hl.env("QT_QPA_PLATFORMTHEME",        "qt6ct")
hl.env("ELECTRON_OZONE_PLATFORM_HINT","wayland")
