windowrule = suppressevent maximize, class:.*
windowrule = bordercolor rgba(E6C384ff) rgba(DCA561ff) 45deg, class:(nemo)
windowrule = bordercolor rgba(E6C384ff) rgba(DCA561ff) 45deg, class:(firefox)
windowrule = bordercolor rgba(791F8AFF) rgba(a745bbff) 45deg, class:(obsidian)

windowrule = float, class:^(org.gnome.Nautilus)$
windowrule = float, class:^(xdg-desktop-portal-gtk)$
windowrule = float, class:^(org.kde.kate)$
windowrule = noanim, class:^(flameshot)$
windowrule = float, class:^(flameshot)$
windowrule = move 0 0, class:^(flameshot)$
windowrule = pin, class:^(flameshot)$

windowrule = monitor 1, class:^(flameshot)$
windowrule = noborder, class:(Google-chrome)
windowrule = opacity 0.90 0.90,class:(Google-chrome)

#Workspaces rules
workspace = special:toolbox, rounding:false, decorate:false, border:false
